# Generated by Django 4.1.4 on 2023-01-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customer_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category_id',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
