# Generated by Django 4.1.4 on 2023-01-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_product_category_id_product_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartDetail',
            new_name='Cartd',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
