# Generated by Django 4.1.4 on 2023-01-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_cartdetail_cartd_rename_cart_id_order_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartd',
            new_name='CartInfo',
        ),
    ]
