# Generated by Django 4.1.4 on 2023-01-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_cartinfo_cartitem_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='user_id',
            new_name='user',
        ),
    ]
