# Generated by Django 4.1.4 on 2023-01-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_userprofile_user'),
        ('main_app', '0008_rename_user_id_productcategory_user'),
    ]

    operations = [
    ]
