# Generated by Django 4.1.5 on 2023-01-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20230110_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
    ]
