# Generated by Django 4.1.5 on 2023-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_user_id_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['customer']},
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
