# Generated by Django 4.1.5 on 2023-01-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_order_order_status_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'approved')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'confirmed')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('B', 'benefit'), ('C', 'card'), ('M', 'cash')], default='B', max_length=1),
        ),
    ]
